// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Presences.Infrastructure;

namespace Presences.Infrastructure.Migrations
{
    [DbContext(typeof(PresencesContext))]
    [Migration("20211116132416_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Presences.Domain.Moment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MomentType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Moments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MomentType = 0,
                            Name = "PE .NET Expert"
                        },
                        new
                        {
                            Id = 2,
                            MomentType = 1,
                            Name = "Examen .NET Expert"
                        },
                        new
                        {
                            Id = 3,
                            MomentType = 0,
                            Name = "PE Mobile Development"
                        },
                        new
                        {
                            Id = 4,
                            MomentType = 1,
                            Name = "Examen Mobile Development"
                        },
                        new
                        {
                            Id = 5,
                            MomentType = 1,
                            Name = "Examen Web Expert"
                        },
                        new
                        {
                            Id = 6,
                            MomentType = 1,
                            Name = "Examen Java Expert"
                        });
                });

            modelBuilder.Entity("Presences.Domain.MomentStudent", b =>
                {
                    b.Property<int>("MomentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("MomentId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("MomentStudents");
                });

            modelBuilder.Entity("Presences.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 50317565,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7fcd9135-d496-4548-8269-425cde28e2ae",
                            EmailConfirmed = false,
                            FirstName = "Jochem",
                            LastName = "Beckers",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "jochembeckers"
                        },
                        new
                        {
                            Id = 50531122,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3a6dced0-718d-497e-9124-1a9030fc248a",
                            EmailConfirmed = false,
                            FirstName = "Pieter",
                            LastName = "Geerts",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "pietergeerts"
                        },
                        new
                        {
                            Id = 84082214,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "94a6ee2e-26ae-4de9-b034-8160b5ff623c",
                            EmailConfirmed = false,
                            FirstName = "Chris",
                            LastName = "Goyens",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "chrisgoyens"
                        },
                        new
                        {
                            Id = 49014562,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "96fc34ef-55c3-46f3-b621-433f5f454ae5",
                            EmailConfirmed = false,
                            FirstName = "Steven",
                            LastName = "Jacquemin",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "stevenjacquemin"
                        },
                        new
                        {
                            Id = 91813987,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3ae9a9f9-fcc8-42e6-8ac4-2a97567a97f5",
                            EmailConfirmed = false,
                            FirstName = "Geoffrey",
                            LastName = "Jorissen",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "geoffreyjorissen"
                        },
                        new
                        {
                            Id = 63117126,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bc370375-6a04-4326-b001-1d533844a3f2",
                            EmailConfirmed = false,
                            FirstName = "Rob",
                            LastName = "Jorissen",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "robjorissen"
                        },
                        new
                        {
                            Id = 30441858,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c6fb7153-bccb-431d-9cf9-e965ff535f3a",
                            EmailConfirmed = false,
                            FirstName = "Sigrid",
                            LastName = "Meesters",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "sigridmeesters"
                        },
                        new
                        {
                            Id = 52449732,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca86135a-3791-4348-814d-fc0142116449",
                            EmailConfirmed = false,
                            FirstName = "Wouter",
                            LastName = "Paps",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "wouterpaps"
                        },
                        new
                        {
                            Id = 15559621,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "93dcab15-3194-45fc-983b-2073badd9f9b",
                            EmailConfirmed = false,
                            FirstName = "Robby",
                            LastName = "Quintiens",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "robbyquintiens"
                        },
                        new
                        {
                            Id = 46559947,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aaff572d-835c-4133-899a-08bf7bbe6116",
                            EmailConfirmed = false,
                            FirstName = "Nadine",
                            LastName = "Vaesen",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "nadinevaesen"
                        },
                        new
                        {
                            Id = 11903691,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a7b9661-f864-4424-bbdd-ad27883b9173",
                            EmailConfirmed = false,
                            FirstName = "Jan",
                            LastName = "Vinkenroye",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "janvinkenroye"
                        },
                        new
                        {
                            Id = 97305845,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6e7782c9-7e48-4159-b122-7cba67c0aacd",
                            EmailConfirmed = false,
                            FirstName = "Jeff",
                            LastName = "Willen",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "jeffwillen"
                        });
                });

            modelBuilder.Entity("Presences.Domain.MomentStudent", b =>
                {
                    b.HasOne("Presences.Domain.Moment", "Moment")
                        .WithMany("MomentStudents")
                        .HasForeignKey("MomentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Presences.Domain.Student", "Student")
                        .WithMany("MomentStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Presences.Domain.Moment", b =>
                {
                    b.Navigation("MomentStudents");
                });

            modelBuilder.Entity("Presences.Domain.Student", b =>
                {
                    b.Navigation("MomentStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
