// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Presences.Infrastructure;

#nullable disable

namespace Presences.Infrastructure.Migrations
{
    [DbContext(typeof(PresencesContext))]
    partial class PresencesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Presences.Domain.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 23
                        });
                });

            modelBuilder.Entity("Presences.Domain.Lector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("lectors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 17
                        },
                        new
                        {
                            Id = 2,
                            UserId = 18
                        },
                        new
                        {
                            Id = 3,
                            UserId = 19
                        },
                        new
                        {
                            Id = 4,
                            UserId = 20
                        },
                        new
                        {
                            Id = 5,
                            UserId = 21
                        },
                        new
                        {
                            Id = 6,
                            UserId = 22
                        });
                });

            modelBuilder.Entity("Presences.Domain.Moment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<int>("LectorForeignKey")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location");

                    b.Property<int>("MomentType")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LectorForeignKey");

                    b.ToTable("moments", (string)null);
                });

            modelBuilder.Entity("Presences.Domain.Presence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsBlanco")
                        .HasColumnType("bit");

                    b.Property<int>("MomentForeignKey")
                        .HasColumnType("int");

                    b.Property<int>("StudentForeignKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MomentForeignKey");

                    b.HasIndex("StudentForeignKey");

                    b.ToTable("presences", (string)null);
                });

            modelBuilder.Entity("Presences.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            UserId = 16
                        });
                });

            modelBuilder.Entity("Presences.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Jochem",
                            LastName = "Beckers",
                            Role = 2,
                            UserName = "jochembeckers"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Pieter",
                            LastName = "Geerts",
                            Role = 2,
                            UserName = "pietergeerts"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Chris",
                            LastName = "Goyens",
                            Role = 2,
                            UserName = "chrisgoyens"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Steven",
                            LastName = "Jacquemin",
                            Role = 2,
                            UserName = "stevenjacquemin"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Daisy",
                            LastName = "Jansen",
                            Role = 2,
                            UserName = "daisyjansen"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Geoffrey",
                            LastName = "Jorissen",
                            Role = 2,
                            UserName = "geoffreyjorissen"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Rob",
                            LastName = "Jorissen",
                            Role = 2,
                            UserName = "robjorissen"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Ward",
                            LastName = "Lenaerts",
                            Role = 2,
                            UserName = "wardlenaerts"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Stijn",
                            LastName = "Lenaerts",
                            Role = 2,
                            UserName = "stijnlenaerts"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Sigrid",
                            LastName = "Meesters",
                            Role = 2,
                            UserName = "sigridmeesters"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Enkhjargal",
                            LastName = "Mijid",
                            Role = 2,
                            UserName = "enkhjargalmijid"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Wouter",
                            LastName = "Paps",
                            Role = 2,
                            UserName = "wouterpaps"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Robby",
                            LastName = "Quintiens",
                            Role = 2,
                            UserName = "robbyquintiens"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Nadine",
                            LastName = "Vaesen",
                            Role = 2,
                            UserName = "nadinevaesen"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Jan",
                            LastName = "Vinkenroye",
                            Role = 2,
                            UserName = "janvinkenroye"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Jeff",
                            LastName = "Willen",
                            Role = 2,
                            UserName = "jeffwillen"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Nele",
                            LastName = "Custers",
                            Role = 1,
                            UserName = "nelecusters"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Luc",
                            LastName = "Doumen",
                            Role = 1,
                            UserName = "lucdoumen"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Kris",
                            LastName = "Hermans",
                            Role = 1,
                            UserName = "krishermans"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Dries",
                            LastName = "Swinnen",
                            Role = 1,
                            UserName = "driesswinnen"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Niek",
                            LastName = "Vandael",
                            Role = 1,
                            UserName = "niekvandael"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Jan",
                            LastName = "Willekens",
                            Role = 1,
                            UserName = "janwillekens"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Nathalie",
                            LastName = "Fuchs",
                            Role = 0,
                            UserName = "nathaliefuchs"
                        });
                });

            modelBuilder.Entity("Presences.Domain.Admin", b =>
                {
                    b.HasOne("Presences.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("Presences.Domain.Admin", "UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Presences.Domain.Lector", b =>
                {
                    b.HasOne("Presences.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("Presences.Domain.Lector", "UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Presences.Domain.Moment", b =>
                {
                    b.HasOne("Presences.Domain.Lector", "Lector")
                        .WithMany("OwnedMoments")
                        .HasForeignKey("LectorForeignKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lector");
                });

            modelBuilder.Entity("Presences.Domain.Presence", b =>
                {
                    b.HasOne("Presences.Domain.Moment", "Moment")
                        .WithMany()
                        .HasForeignKey("MomentForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Presences.Domain.Student", "Student")
                        .WithMany("Presences")
                        .HasForeignKey("StudentForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Presences.Domain.Student", b =>
                {
                    b.HasOne("Presences.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("Presences.Domain.Student", "UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Presences.Domain.Lector", b =>
                {
                    b.Navigation("OwnedMoments");
                });

            modelBuilder.Entity("Presences.Domain.Student", b =>
                {
                    b.Navigation("Presences");
                });
#pragma warning restore 612, 618
        }
    }
}
