version: '3.4'

services:
    presences.api:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ConnectionString=DataSource=sqldata;Database=Presences;UserId=sa;Password=P@ssw0rd
        ports:
        - "5000:80"
        - "5001:443"
        volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    sqldata:
        environment:
        - SA_PASSWORD=P@ssw0rd
        - ACCEPT_EULA=Y
        ports:
        - "1433:1433" #make db server accessible for host system on port 1433(Server name: localhost)
        volumes:
        - presences-sqldata:/var/opt/mssql
    
volumes:
    presences-sqldata:
        external: false
